apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-dev.fullname" . }}
  labels:
    {{- include "postgresql-dev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgresql-dev.selectorLabels" . | nindent 4 }}
