{{- if .Values.filer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filer.serviceAccountName" . }}
  labels:
    {{- include "filer.labels" . | nindent 4 }}
{{- end -}}
