apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filer.fullname" . }}
  labels:
    {{- include "filer.labels" . | nindent 4}}
type: Opaque
stringData:
  filer.toml: |
    # A sample TOML config file for SeaweedFS filer store
    # Used with "weed filer" or "weed server -filer"
    # Put this file to one of the location, with descending priority
    #    ./filer.toml
    #    $HOME/.seaweedfs/filer.toml
    #    /etc/seaweedfs/filer.toml

    [memory]
    # local in memory, mostly for testing purpose
    enabled = false

    [leveldb]
    # local on disk, mostly for simple single-machine setup, fairly scalable
    enabled = false
    dir = "/data/"					# directory to store level db files

    [leveldb2]
    # local on disk, mostly for simple single-machine setup, fairly scalable
    # faster than previous leveldb, recommended.
    enabled = true
    dir = "/data/"					# directory to store level db files

    ####################################################
    # multiple filers on shared storage, fairly scalable
    ####################################################

    [mysql]  # or tidb
    # CREATE TABLE IF NOT EXISTS filemeta (
    #   dirhash     BIGINT         COMMENT 'first 64 bits of MD5 hash value of directory field',
    #   name        VARCHAR(1000)  COMMENT 'directory or file name',
    #   directory   TEXT           COMMENT 'full path to parent directory',
    #   meta        LONGBLOB,
    #   PRIMARY KEY (dirhash, name)
    # ) DEFAULT CHARSET=utf8;

    enabled = false
    hostname = "localhost"
    port = 3306
    username = "root"
    password = ""
    database = ""              # create or use an existing database
    connection_max_idle = 2
    connection_max_open = 100

    [postgres] # or cockroachdb
    # CREATE TABLE IF NOT EXISTS filemeta (
    #   dirhash     BIGINT,
    #   name        VARCHAR(65535),
    #   directory   VARCHAR(65535),
    #   meta        bytea,
    #   PRIMARY KEY (dirhash, name)
    # );
    enabled = false
    hostname = "localhost"
    port = 5432
    username = "postgres"
    password = ""
    database = ""              # create or use an existing database
    sslmode = "disable"
    connection_max_idle = 100
    connection_max_open = 100

    [cassandra]
    # CREATE TABLE filemeta (
    #    directory varchar,
    #    name varchar,
    #    meta blob,
    #    PRIMARY KEY (directory, name)
    # ) WITH CLUSTERING ORDER BY (name ASC);
    enabled = false
    keyspace="seaweedfs"
    hosts=[
      "localhost:9042",
    ]

    [redis]
    enabled = false
    address  = "localhost:6379"
    password = ""
    database = 0

    [redis_cluster]
    enabled = false
    addresses = [
      "localhost:30001",
      "localhost:30002",
      "localhost:30003",
      "localhost:30004",
      "localhost:30005",
      "localhost:30006",
    ]
    password = ""

    [etcd]
    enabled = false
    servers = "localhost:2379"
    timeout = "3s"
