{{- if .Values.manager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "manager.serviceAccountName" . }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
{{- end -}}
