apiVersion: v1
kind: Service
metadata:
  name: {{ include "manager.fullname" . }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "manager.selectorLabels" . | nindent 4 }}
  ports:
    - port: 19333
      name: grpc
      protocol: TCP
    - port: 9333
      name: http
      protocol: TCP
