{{- if .Values.s3.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "s3.serviceAccountName" . }}
  labels:
    {{- include "s3.labels" . | nindent 4 }}
{{- end -}}
