apiVersion: v1
kind: Service
metadata:
  name: {{ include "syslog.fullname" . }}
  labels:
    {{- include "syslog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 514
      targetPort: 514
      protocol: UDP
      name: udp
    - port: 601
      targetPort: 601
      protocol: TCP
      name: tcp
    - port: 6514
      targetPort: 6514
      protocol: TCP
      name: tls
  selector:
    {{- include "syslog.selectorLabels" . | nindent 4 }}
